# Generated by Django 3.2.4 on 2021-11-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('username', models.CharField(max_length=50, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
            ],
        ),
    ]
