# Generated by Django 3.2.4 on 2021-11-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBike', models.CharField(max_length=50, verbose_name='nombre bicicleta')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('imgUrl', models.TextField()),
            ],
        ),
    ]
