# Generated by Django 3.2.4 on 2021-12-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_isdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isDriver',
            field=models.CharField(max_length=10, verbose_name='Conductor'),
        ),
    ]
