# Generated by Django 3.2.4 on 2021-12-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_isdriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('patent', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='patente')),
                ('brand', models.CharField(max_length=30, verbose_name='Marca')),
                ('model', models.CharField(max_length=30, verbose_name='Modelo')),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
                ('year', models.IntegerField(verbose_name='Anio')),
            ],
        ),
    ]
