# Generated by Django 3.2.4 on 2021-12-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_vehicle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='user_id',
            field=models.IntegerField(default=None, verbose_name='Id usuario'),
            preserve_default=False,
        ),
    ]
