# Generated by Django 3.2.4 on 2021-12-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211204_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=30, verbose_name='Sede')),
                ('destiny', models.CharField(max_length=60, verbose_name='Destino')),
                ('rate', models.IntegerField(verbose_name='Tarifa')),
                ('user_id', models.IntegerField(verbose_name='Id usuario')),
            ],
        ),
    ]
