# Generated by Django 3.2.4 on 2021-12-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_vehicle_passengers_suscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='passengers_suscribed',
        ),
        migrations.AddField(
            model_name='route',
            name='passengers_suscribed',
            field=models.IntegerField(default=0, verbose_name='Pasajeros suscritos'),
            preserve_default=False,
        ),
    ]
